import type { NextPage } from "next";
import Head from "next/head";
import Card from "../components/Card";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Green commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="pt-4">
        <div className="flex justify-center items-center">
          <Link href={"/leaderboard"}>
            <a className="text-xl text-green-500 underline hover:text-green-600">
              Checkout leaderboard
            </a>
          </Link>
        </div>
        <div className="flex justify-center align-middle items-center flex-wrap mt-8">
          <Card adminCard={false} />
          <Card adminCard={false} />
          <Card adminCard={false} />
        </div>
      </main>
    </div>
  );
};

export default Home;
